import { randomBytes } from 'node:crypto';
import { desc, sql } from 'drizzle-orm';
import {
  type AnySQLiteColumn,
  check,
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';

/**
 * Data Layer schema (SPEC-002). This file is the ONLY place tables are
 * defined; migrations under drizzle/** are generated from it
 * (`drizzle-kit generate`) and are an internal artifact, not a contract.
 *
 * Conventions (SPEC-002 "Conventions", binding across every table):
 *  - every timestamp column is INTEGER unix milliseconds UTC (never TEXT,
 *    never local time) — column names end in `_at`.
 *  - every primary key is a UUIDv7 TEXT value, generated server-side via
 *    `generateUuidV7` below, so `id` is a valid, time-sortable cursor
 *    tiebreak. The one deliberate exception is `sessions.id`, which SPEC-002
 *    specifies as a 256-bit random base64url value (it doubles as the
 *    session cookie, so it must not be time-derived/guessable) — that value
 *    is generated by the sessions repository, not defaulted here.
 */

/**
 * Generates a UUIDv7: a 48-bit big-endian unix-ms timestamp, a 4-bit version
 * (0111), 12 bits of random `rand_a`, a 2-bit variant (10), and 62 bits of
 * random `rand_b` (RFC 9562). Time-ordered, so lexical string sort matches
 * creation order.
 */
export function generateUuidV7(): string {
  const unixTsMs = BigInt(Date.now());
  const rand = randomBytes(10);
  const bytes = new Uint8Array(16);

  bytes[0] = Number((unixTsMs >> 40n) & 0xffn);
  bytes[1] = Number((unixTsMs >> 32n) & 0xffn);
  bytes[2] = Number((unixTsMs >> 24n) & 0xffn);
  bytes[3] = Number((unixTsMs >> 16n) & 0xffn);
  bytes[4] = Number((unixTsMs >> 8n) & 0xffn);
  bytes[5] = Number(unixTsMs & 0xffn);

  // version 7 in the high nibble of byte 6; top 4 bits of rand_a in the low nibble
  bytes[6] = 0x70 | (rand[0]! & 0x0f);
  bytes[7] = rand[1]!;
  // variant 10 in the top 2 bits of byte 8
  bytes[8] = 0x80 | (rand[2]! & 0x3f);
  bytes[9] = rand[3]!;
  bytes[10] = rand[4]!;
  bytes[11] = rand[5]!;
  bytes[12] = rand[6]!;
  bytes[13] = rand[7]!;
  bytes[14] = rand[8]!;
  bytes[15] = rand[9]!;

  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

const idColumn = () => text('id').primaryKey().$defaultFn(generateUuidV7);

// ---------------------------------------------------------------------------
// users
// ---------------------------------------------------------------------------
export const users = sqliteTable('users', {
  id: idColumn(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  handle: text('handle').notNull().unique(),
  displayName: text('display_name').notNull(),
  bio: text('bio'),
  avatarUploadId: text('avatar_upload_id').references((): AnySQLiteColumn => uploads.id),
  coverUploadId: text('cover_upload_id').references((): AnySQLiteColumn => uploads.id),
  socialTwitter: text('social_twitter'),
  socialGithub: text('social_github'),
  socialWebsite: text('social_website'),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
});

// ---------------------------------------------------------------------------
// sessions
// ---------------------------------------------------------------------------
export const sessions = sqliteTable('sessions', {
  // Not a UUIDv7 default — see generateUuidV7 doc comment above.
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  expiresAt: integer('expires_at').notNull(),
  createdAt: integer('created_at').notNull(),
  lastSeenAt: integer('last_seen_at').notNull(),
});

// ---------------------------------------------------------------------------
// articles
// ---------------------------------------------------------------------------
export const articles = sqliteTable(
  'articles',
  {
    id: idColumn(),
    authorId: text('author_id')
      .notNull()
      .references(() => users.id),
    // slug/bodyHtml/excerpt/wordCount/readTimeMinutes are DERIVED columns.
    // deriveArticleFields(bodyJson) in src/lib/article/derive.ts (a later
    // slice — out of this module's file scope) is their ONLY writer;
    // repositories in this module accept them as caller-supplied values on
    // create/update and never compute them.
    slug: text('slug').notNull().unique(),
    title: text('title').notNull(),
    subtitle: text('subtitle'),
    bodyJson: text('body_json').notNull(),
    bodyHtml: text('body_html').notNull(),
    excerpt: text('excerpt').notNull(),
    wordCount: integer('word_count').notNull(),
    readTimeMinutes: integer('read_time_minutes').notNull(),
    coverUploadId: text('cover_upload_id').references(() => uploads.id),
    status: text('status', { enum: ['draft', 'published'] }).notNull(),
    publishedAt: integer('published_at'),
    clapTotal: integer('clap_total').notNull().default(0),
    commentCount: integer('comment_count').notNull().default(0),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
  },
  (table) => [
    index('idx_articles_feed').on(table.status, desc(table.publishedAt), desc(table.id)),
    index('idx_articles_author').on(table.authorId, table.status, desc(table.publishedAt)),
  ],
);

// ---------------------------------------------------------------------------
// tags / article_tags
// ---------------------------------------------------------------------------
export const tags = sqliteTable('tags', {
  id: idColumn(),
  slug: text('slug').notNull().unique(),
  displayName: text('display_name').notNull(),
  createdAt: integer('created_at').notNull(),
});

export const articleTags = sqliteTable(
  'article_tags',
  {
    articleId: text('article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    tagId: text('tag_id')
      .notNull()
      .references(() => tags.id, { onDelete: 'cascade' }),
  },
  (table) => [
    primaryKey({ columns: [table.articleId, table.tagId] }),
    index('idx_article_tags_tag').on(table.tagId, table.articleId),
  ],
);

// ---------------------------------------------------------------------------
// claps
// ---------------------------------------------------------------------------
export const claps = sqliteTable(
  'claps',
  {
    id: idColumn(),
    articleId: text('article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    count: integer('count').notNull(),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('idx_claps_article_user').on(table.articleId, table.userId),
    check('claps_count_range', sql`${table.count} BETWEEN 1 AND 50`),
  ],
);

// ---------------------------------------------------------------------------
// comments
// ---------------------------------------------------------------------------
export const comments = sqliteTable(
  'comments',
  {
    id: idColumn(),
    articleId: text('article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    authorId: text('author_id')
      .notNull()
      .references(() => users.id),
    parentId: text('parent_id').references((): AnySQLiteColumn => comments.id),
    bodyText: text('body_text').notNull(),
    createdAt: integer('created_at').notNull(),
    deletedAt: integer('deleted_at'),
  },
  (table) => [index('idx_comments_article').on(table.articleId, table.createdAt)],
);

// ---------------------------------------------------------------------------
// follows
// ---------------------------------------------------------------------------
export const follows = sqliteTable(
  'follows',
  {
    followerId: text('follower_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    followingId: text('following_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: integer('created_at').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.followerId, table.followingId] }),
    index('idx_follows_follower').on(table.followerId, desc(table.createdAt)),
    check('follows_no_self', sql`${table.followerId} <> ${table.followingId}`),
  ],
);

// ---------------------------------------------------------------------------
// uploads
// ---------------------------------------------------------------------------
export const uploads = sqliteTable(
  'uploads',
  {
    id: idColumn(),
    ownerId: text('owner_id')
      .notNull()
      .references(() => users.id),
    diskPath: text('disk_path').notNull().unique(),
    mime: text('mime').notNull(),
    bytes: integer('bytes').notNull(),
    width: integer('width'),
    height: integer('height'),
    kind: text('kind', { enum: ['avatar', 'cover', 'article_image'] }).notNull(),
    createdAt: integer('created_at').notNull(),
  },
  (table) => [check('uploads_max_bytes', sql`${table.bytes} <= 5242880`)],
);

// ---------------------------------------------------------------------------
// conversations / conversation_participants / messages
// ---------------------------------------------------------------------------
export const conversations = sqliteTable('conversations', {
  id: idColumn(),
  // Canonical uniqueness key: min(user_a,user_b) || ':' || max(user_a,user_b)
  // — makes "message this author" idempotent (SPEC-002).
  pairKey: text('pair_key').notNull().unique(),
  createdAt: integer('created_at').notNull(),
  lastMessageAt: integer('last_message_at'),
});

export const conversationParticipants = sqliteTable(
  'conversation_participants',
  {
    conversationId: text('conversation_id')
      .notNull()
      .references(() => conversations.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    lastReadAt: integer('last_read_at'),
  },
  (table) => [primaryKey({ columns: [table.conversationId, table.userId] })],
);

export const messages = sqliteTable(
  'messages',
  {
    id: idColumn(),
    conversationId: text('conversation_id')
      .notNull()
      .references(() => conversations.id, { onDelete: 'cascade' }),
    senderId: text('sender_id')
      .notNull()
      .references(() => users.id),
    bodyText: text('body_text').notNull(),
    createdAt: integer('created_at').notNull(),
  },
  (table) => [index('idx_messages_conv').on(table.conversationId, desc(table.createdAt))],
);

// ---------------------------------------------------------------------------
// notifications
// ---------------------------------------------------------------------------
export const notifications = sqliteTable(
  'notifications',
  {
    id: idColumn(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    type: text('type', {
      enum: ['clap', 'comment', 'reply', 'follow', 'message'],
    }).notNull(),
    actorId: text('actor_id')
      .notNull()
      .references(() => users.id),
    articleId: text('article_id').references(() => articles.id, { onDelete: 'cascade' }),
    commentId: text('comment_id').references(() => comments.id, { onDelete: 'cascade' }),
    messageId: text('message_id').references(() => messages.id, { onDelete: 'cascade' }),
    readAt: integer('read_at'),
    createdAt: integer('created_at').notNull(),
  },
  (table) => [
    index('idx_notifications_user').on(table.userId, table.readAt, desc(table.createdAt)),
  ],
);

// ---------------------------------------------------------------------------
// password_reset_tokens
// ---------------------------------------------------------------------------
export const passwordResetTokens = sqliteTable('password_reset_tokens', {
  id: idColumn(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  tokenHash: text('token_hash').notNull().unique(),
  expiresAt: integer('expires_at').notNull(),
  usedAt: integer('used_at'),
  createdAt: integer('created_at').notNull(),
});
